-- Add substacks and podcast RSS feeds for the Currents section
INSERT INTO news_sources (name, url, rss_feed_url, category, is_active) VALUES
('The Line (Substack)', 'https://theline.substack.com', 'https://theline.substack.com/feed', 'Commentary', true),
('Canadaland Podcast', 'https://www.canadaland.com', 'https://feeds.soundcloud.com/users/soundcloud:users:85416094/sounds.rss', 'Commentary', true),
('The Hub (Substack)', 'https://thehub.ca', 'https://thehub.ca/feed/', 'Commentary', true),
('The Dispatch (Substack)', 'https://thedispatch.com', 'https://thedispatch.com/feed/', 'Commentary', true);
('338Canada', 'https://www.338canada.ca/', 'https://www.338canada.ca/feed/', 'Commentary', true),
('David Coletto (Substack)', 'https://davidcoletto.substack.com', 'https://davidcoletto.substack.com/feed', 'Commentary', true),
('The Writ', 'https://www.thewrit.ca/', 'https://www.thewrit.ca/feed/', 'Commentary', true),
('The Thursday Question (Substack)', 'https://thethursdayquestion.substack.com', 'https://thethursdayquestion.substack.com/feed', 'Commentary', true),
('Read the Line', 'https://www.readtheline.ca/', 'https://www.readtheline.ca/feed/', 'Commentary', true),
('Orbit Policy (Substack)', 'https://orbitpolicy.substack.com', 'https://orbitpolicy.substack.com/feed', 'Commentary', true),
('Metaviews (Substack)', 'https://metaviews.substack.com', 'https://metaviews.substack.com/feed', 'Commentary', true),
('David Moscrop', 'https://www.davidmoscrop.com/', 'https://www.davidmoscrop.com/feed/', 'Commentary', true),
('Bug-eyed and Shameless (Substack)', 'https://www.bugeyedandshameless.com/', 'https://www.bugeyedandshameless.com/feed/', 'Commentary', true),
('Paul Wells (Substack)', 'https://paulwells.substack.com', 'https://paulwells.substack.com/feed', 'Commentary', true),
('Toronto History Weekly (Substack)', 'https://torontohistory.substack.com', 'https://torontohistory.substack.com/feed', 'Commentary', true),
('Art Forecast (Substack)', 'https://artforecast.substack.com', 'https://artforecast.substack.com/feed', 'Commentary', true),
('Future of Workers (Substack)', 'https://futureofworkers.substack.com', 'https://futureofworkers.substack.com/feed', 'Commentary', true),
('City Hall Watcher (Substack)', 'https://toronto.cityhallwatcher.com', 'https://toronto.cityhallwatcher.com/feed', 'Commentary', true),
('1236 (Substack)', 'https://1236.substack.com', 'https://1236.substack.com/feed', 'Commentary', true),
('Hatchet (Substack)', 'https://hatchetmedia.substack.com', 'https://hatchetmedia.substack.com/feed', 'Commentary', true),
('The Orchard', 'https://www.readtheorchard.org/', 'https://www.readtheorchard.org/feed/', 'Commentary', true),
('Ed Hollett (Substack)', 'https://edhollett.substack.com', 'https://edhollett.substack.com/feed', 'Commentary', true),
('Emmett Macfarlane (Substack)', 'https://emmettmacfarlane.substack.com', 'https://emmettmacfarlane.substack.com/feed', 'Commentary', true),
('Daveberta (Substack)', 'https://daveberta.substack.com', 'https://daveberta.substack.com/feed', 'Commentary', true),
('Alberta Politics (Substack)', 'https://albertapolitics.substack.com', 'https://albertapolitics.substack.com/feed', 'Commentary', true),
('Scrimshaw Unscripted (Substack)', 'https://scrimshawunscripted.substack.com', 'https://scrimshawunscripted.substack.com/feed', 'Commentary', true);
